apiVersion: v1
kind: Pod
metadata:
  name: nginx-annotations
  labels:
    environment: production
  annotations:
    mianotation: valordemianotacion
    basededatos: bbdd1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
