apiVersion: v1
kind: Pod
metadata:
  name: nginx-latest-metadata
  labels:
    project: pagina_web
    environment: testing
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
