apiVersion: v1
kind: Pod
metadata:
  name: startup-http
spec:
  containers:
  - name: startup
    image: nginx:latest
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
