apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: nginx:latest
    livenessProbe:
      exec:
        command:
        - curl
        - localhost
      initialDelaySeconds: 20
      periodSeconds: 5
