apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-volumes-common
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "web-volumes-common"
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      volumes:
        - name: common
          persistentVolumeClaim:
            claimName: www-common
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-web-volumes
          mountPath: /datos/
        - name: common
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www-web-volumes
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "manual"
      resources:
        requests:
          storage: 1Gi
